Table music already exists. Skipping table creation.
Traceback (most recent call last):
  File "application.py", line 305, in <module>
    load_data_to_table()  # Load data from a2.json into the table if it's empty
  File "application.py", line 215, in load_data_to_table
    table.put_item(Item=item)
  File "/usr/local/lib/python3.8/dist-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/client.py", line 986, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 199, in _send_request
    success_response, exception = self._get_response(
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 241, in _get_response
    success_response, exception = self._do_get_response(
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 465, in send
    urllib_response = conn.urlopen(
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/thomas.lambert/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
